name: Meson Build and Test

on:
  push:
    branches:
      - main  # Set this to the branches where you want to run CI
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # You can change this to the required OS

    steps:
    - uses: actions/checkout@v2
      name: Check out repository code

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'  # Specify the Python version. Meson requires Python.

    - name: Install Meson and Ninja
      run: |
        python -m pip install --upgrade pip
        pip install meson ninja  # Install Meson and Ninja

    - name: Configure Meson Build
      run: meson setup build/

    - name: Build
      run: meson compile -C build/

    - name: Test
      run: meson test -C build/
     


